name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Verify Dependencies
        run: go mod verify

      - name: Build
        run: go build

      - name: test
        run: ls

      - name: Move compiled go executable
        uses: garygrossgarten/github-action-scp@release
        with:
          local: go-static-host
          remote: go-static-host
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}`