name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0'
      - run: go build

      - name: Move compiled go executable
        uses: garygrossgarten/github-action-scp@release
        with:
          local: go-static-host
          remote: go-static-host
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}